stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
    params:
    - data_ingestion.test_size
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/preprocess
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/preprocess
    - src/feature_engineering.py
    outs:
    - artifacts/tokenizer.pkl
    - artifacts/x_train_pad.npy
    - artifacts/x_test_pad.npy
    - artifacts/y_train.npy
    - artifacts/y_test.npy
    params:
    - feature_engineering.num_words
    - feature_engineering.max_len
  model_training:
    cmd: python src/model_training.py
    deps:
    - artifacts/tokenizer.pkl
    - artifacts/x_train_pad.npy
    - artifacts/x_test_pad.npy
    - artifacts/y_train.npy
    - artifacts/y_test.npy
    - src/model_training.py
    outs:
    - artifacts/cnn_model.h5
    params:
    - model_training.vocab_size
    - model_training.max_len
    - model_training.output_dim
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - artifacts/cnn_model.h5
    - artifacts/x_train_pad.npy
    - artifacts/x_test_pad.npy
    - artifacts/y_train.npy
    - artifacts/y_test.npy
    - src/model_evaluation.py
    outs:
    - artifacts/metrics.json
   

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
