data_ingestion: 
  test_size: 0.20

mongodb:
  CONNECTION_URL: "mongodb+srv://vaishnavibarolia_db_user:rDpnzMgseYw6bdnA@cluster0.b5qy2gy.mongodb.net/?appName=Cluster0"
  DB_NAME: "Toxic_comment"
  COLLECTION_NAME: "Toxic_Comment_Data"
  batch_size: 10000


feature_engineering :  
   num_words: 5000   #maximum number of words for tokenize
   max_len: 100          #maximum sequence length for padding

model_training :
  vocab_size: 5000       #must match num_words in feature engineering
  max_len: 100             #must match max_len in faeture engineering 
  output_dim: 100           #embedding dim or output layer units




  